apiVersion: apps/v1
kind: Deployment
metadata:
  name: fhir-client
  labels: { app: fhir-client }
spec:
  replicas: 1
  selector: { matchLabels: { app: fhir-client } }
  template:
    metadata: { labels: { app: fhir-client } }
    spec:
      containers:
        - name: fhir-client
          image: <acr_login>/healthcopilot/fhir-client:1.0
          env:
            - { name: FHIR_CLIENT_ID, valueFrom: { secretKeyRef: { name: copilot-secrets, key: fhir_client_id } } }
            - { name: FHIR_CLIENT_SECRET, valueFrom: { secretKeyRef: { name: copilot-secrets, key: fhir_client_secret } } }
            - { name: FHIR_AUTH_URL, valueFrom: { secretKeyRef: { name: copilot-secrets, key: fhir_auth_url } } }
            - { name: FHIR_ENDPOINT, valueFrom: { secretKeyRef: { name: copilot-secrets, key: fhir_endpoint } } }
